---
- hosts: 192.168.148.133
  tasks:
    - name: install net-tools
      apt:
        name: net-tools
        state: latest
      become: yes
    - name: install ddclient
      apt:
        name: ddclient
        state: latest
      become: yes
    - name: add pritunl apt key1
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    - name: add pritunl apt key2
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: E162F504A20CDF15827F718D4B7C549A058F8B6B
    - name: add mongodb apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
      become: yes
    - name: create pritunl repo file for pritunl
      apt_repository:
        repo: deb https://repo.pritunl.com/stable/apt focal main
        state: present
        update_cache: no
        filename: pritunl.list
    - name: create pritunl repo file for mongodb
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.2 multiverse
        state: present
        update_cache: no
        filename: mongodb-org-4.2.list
      become: yes
    - name: apt update
      apt: update_cache=true
      become: yes
    - name: install pritunl server
      apt:
        name: pritunl
        state: latest
      become: yes
    - name: install mongodb server
      apt:
        name: mongodb-server
        state: latest
      become: yes
    - name: start/enable pritunl server
      systemd:
        name: pritunl
        state: started
        enabled: yes
      become: yes
    - name: start/enable mongodb server
      systemd:
        name: mongodb
        state: started
        enabled: yes
      become: yes

