---
- hosts: 192.168.148.133
  tasks:
    - name: install net-tools
      apt:
        name: net-tools
        state: latest
      become: yes
    - name: install ddclient
      apt:
        name: ddclient
        state: latest
      become: yes
    - name: add pritunl apt key1
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    - name: add pritunl apt key2
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: E162F504A20CDF15827F718D4B7C549A058F8B6B
    - name: add mongodb apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
      become: yes
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      become: yes
    - name: create pritunl repo file for pritunl
      apt_repository:
        repo: deb https://repo.pritunl.com/stable/apt focal main
        state: present
        update_cache: no
        filename: pritunl.list
    - name: create pritunl repo file for mongodb
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.2 multiverse
        state: present
        update_cache: no
        filename: mongodb-org-4.2.list
    - name: create docker repo file
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: no
        filename: docker.list
      become: yes
    - name: apt update
      apt: update_cache=true
      ignore_errors: yes
      become: yes
    - name: install pritunl server
      apt:
        name: pritunl
        state: present
      become: yes
    - name: install mongodb server
      apt:
        name: mongodb-server
        state: present
      become: yes
    - name: start/enable pritunl server
      systemd:
        name: pritunl
        state: started
        enabled: yes
      become: yes
    - name: start/enable mongodb server
      systemd:
        name: mongodb
        state: started
        enabled: yes
      become: yes
    - name: install docker engine dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      become: yes
    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes
    - name: docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: download Outline server install script
      get_url: https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh
    - name: execute Outline server install script
      shell: /tmp/install_server.sh
      become: yes

